language: php
dist: precise

php:
    - 5.6
    - 7.0
    - 7.1

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - php artisan key:generate

script:
  - vendor/bin/phpunit --bootstrap bootstrap/autoload.php --coverage-text --coverage-clover=coverage.clover